import React, { useState, useRef } from 'react';
import {
  X,
  Download,
  Upload,
  FileCode,
  FileJson,
  Image as ImageIcon,
  Check,
  Copy,
  AlertCircle,
  FileText,
  Sparkles,
} from 'lucide-react';
import { DynamicVariable, EngineType, SavedConfiguration } from '../types';
import { variablesToMap } from '../engines/presets';

interface ExportImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeTab?: 'export' | 'import';
  engine: EngineType;
  variables: DynamicVariable[];
  onImportConfig: (data: { engine: EngineType; variables: DynamicVariable[]; name?: string }) => void;
}

export const ExportImportModal: React.FC<ExportImportModalProps> = ({
  isOpen,
  onClose,
  activeTab: initialTab = 'export',
  engine,
  variables,
  onImportConfig,
}) => {
  const [tab, setTab] = useState<'export' | 'import'>(initialTab);
  const [exportFormat, setExportFormat] = useState<'json' | 'html' | 'png' | 'svg'>('json');
  const [copied, setCopied] = useState(false);
  const [importError, setImportError] = useState<string | null>(null);
  const [importSuccess, setImportSuccess] = useState<string | null>(null);
  const [pasteJsonText, setPasteJsonText] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  if (!isOpen) return null;

  const varMap = variablesToMap(variables);

  // Generate complete project JSON object
  const getProjectJsonObject = () => {
    return {
      version: '1.0.0',
      generator: 'Pts.js Visualization Randomizer',
      createdAt: new Date().toISOString(),
      engine,
      variables,
      stats: {
        totalVariables: variables.length,
        lockedCount: variables.filter((v) => v.isLocked).length,
      },
    };
  };

  // Generate standalone runnable HTML file with Pts.js CDN
  const getStandaloneHtmlCode = () => {
    const jsonVars = JSON.stringify(varMap, null, 2);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pts.js Generative Export - ${engine}</title>
  <script src="https://unpkg.com/pts/dist/pts.min.js"><\/script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body { width: 100%; height: 100%; overflow: hidden; background: ${varMap.bgColor || '#090a0f'}; }
    #pt { width: 100vw; height: 100vh; display: block; }
  </style>
</head>
<body>
  <div id="pt"></div>

  <script>
    // Configuration generated by Pts.js Visualization Randomizer
    const CONFIG = ${jsonVars};

    const { CanvasSpace, CanvasForm, Pt, Group, Curve, Geom } = Pts;
    const space = new CanvasSpace("#pt").setup({ bgcolor: CONFIG.bgColor || "#090a0f", resize: true });
    const form = space.getForm();

    let particles = [];
    const count = CONFIG.particleCount || CONFIG.nodeCount || CONFIG.ribbonCount || 120;

    space.add({
      start: (bound) => {
        particles = [];
        for (let i = 0; i < count; i++) {
          const x = Math.random() * bound.width;
          const y = Math.random() * bound.height;
          const speed = (CONFIG.speed || 3.0) * (0.6 + Math.random() * 0.8);
          const angle = Math.random() * Math.PI * 2;
          particles.push({
            pos: new Pt(x, y),
            vel: new Pt(Math.cos(angle) * speed, Math.sin(angle) * speed),
            acc: new Pt(0, 0),
            home: new Pt(x, y),
            color: i % 2 === 0 ? (CONFIG.primaryColor || "#00f0ff") : (CONFIG.secondaryColor || "#ff0077"),
            history: []
          });
        }
      },

      animate: (time, ftime) => {
        const bound = space.size;
        const w = bound.x;
        const h = bound.y;
        const ctx = form.ctx;
        if (!ctx) return;

        // Trail persistence
        ctx.fillStyle = CONFIG.bgColor || "#090a0f";
        ctx.globalAlpha = CONFIG.trailFade || 0.2;
        ctx.fillRect(0, 0, w, h);
        ctx.globalAlpha = 1.0;

        const t = time / 1000;
        const pointer = space.pointer;

        // Draw and update
        for (let i = 0; i < particles.length; i++) {
          const p = particles[i];
          const angle = Math.sin(p.pos.x * 0.005 + t) * Math.PI;
          p.acc = new Pt(Math.cos(angle) * 0.4, Math.sin(angle) * 0.4);

          if (pointer.x > 0) {
            const dir = pointer.$subtract(p.pos);
            const dist = dir.magnitude();
            if (dist < 250) {
              p.acc.add(dir.unit().multiply((250 - dist) / 250 * (CONFIG.gravity || 0.8)));
            }
          }

          p.vel.add(p.acc).multiply(CONFIG.damping || 0.95);
          p.pos.add(p.vel);

          if (p.pos.x < 0) p.pos.x = w;
          if (p.pos.x > w) p.pos.x = 0;
          if (p.pos.y < 0) p.pos.y = h;
          if (p.pos.y > h) p.pos.y = 0;

          form.fill(p.color).point(p.pos, CONFIG.particleRadius || 3.5, "circle");
        }
      }
    });

    space.bindMouse().bindTouch().play();
  <\/script>
</body>
</html>`;
  };

  // Generate SVG vector code
  const getSvgCode = () => {
    const bg = varMap.bgColor || '#090a0f';
    const pCol = varMap.primaryColor || '#00f0ff';
    const sCol = varMap.secondaryColor || '#ff0077';
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800" width="100%" height="100%">
  <rect width="1200" height="800" fill="${bg}" />
  <defs>
    <linearGradient id="ptsGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="${pCol}" />
      <stop offset="100%" stop-color="${sCol}" />
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="8" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <!-- Generated by Pts.js Visualization Randomizer (${engine}) -->
  <g filter="url(#glow)">
    <circle cx="600" cy="400" r="${varMap.particleRadius ? varMap.particleRadius * 12 : 60}" fill="url(#ptsGrad)" opacity="0.8" />
  </g>
</svg>`;
  };

  // Handle Export Action
  const handleExport = () => {
    if (exportFormat === 'json') {
      const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(getProjectJsonObject(), null, 2));
      const a = document.createElement('a');
      a.href = dataStr;
      a.download = `pts-project-${engine}-${Date.now()}.json`;
      a.click();
    } else if (exportFormat === 'html') {
      const dataStr = 'data:text/html;charset=utf-8,' + encodeURIComponent(getStandaloneHtmlCode());
      const a = document.createElement('a');
      a.href = dataStr;
      a.download = `pts-standalone-${engine}-${Date.now()}.html`;
      a.click();
    } else if (exportFormat === 'svg') {
      const dataStr = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(getSvgCode());
      const a = document.createElement('a');
      a.href = dataStr;
      a.download = `pts-vector-${engine}-${Date.now()}.svg`;
      a.click();
    } else if (exportFormat === 'png') {
      const canvas = document.getElementById('pts-main-canvas') as HTMLCanvasElement;
      if (canvas) {
        const a = document.createElement('a');
        a.href = canvas.toDataURL('image/png');
        a.download = `pts-render-${engine}-${Date.now()}.png`;
        a.click();
      }
    }
  };

  // Copy code/json to clipboard
  const handleCopy = () => {
    let content = '';
    if (exportFormat === 'json') {
      content = JSON.stringify(getProjectJsonObject(), null, 2);
    } else if (exportFormat === 'html') {
      content = getStandaloneHtmlCode();
    } else if (exportFormat === 'svg') {
      content = getSvgCode();
    }
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Process imported JSON
  const processImportData = (parsed: any) => {
    setImportError(null);
    setImportSuccess(null);

    try {
      // Validate schema
      if (!parsed || typeof parsed !== 'object') {
        throw new Error('Invalid JSON format: Must be an object.');
      }

      // Check if variables array exists
      const importedVars: DynamicVariable[] = parsed.variables || [];
      if (!Array.isArray(importedVars) || importedVars.length === 0) {
        throw new Error('Project file missing dynamic variables array.');
      }

      const importedEngine: EngineType = parsed.engine || engine;

      onImportConfig({
        engine: importedEngine,
        variables: importedVars,
        name: parsed.name,
      });

      setImportSuccess(`Successfully imported ${importedVars.length} parameters for ${importedEngine}!`);
      setTimeout(() => {
        onClose();
      }, 1200);
    } catch (err: any) {
      setImportError(err.message || 'Failed to parse configuration file.');
    }
  };

  // File Upload Handler
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        processImportData(parsed);
      } catch (err) {
        setImportError('Invalid JSON file. Please check file content.');
      }
    };
    reader.readAsText(file);
  };

  // Paste Text Handler
  const handlePasteSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!pasteJsonText.trim()) return;
    try {
      const parsed = JSON.parse(pasteJsonText);
      processImportData(parsed);
    } catch (err) {
      setImportError('Failed to parse JSON string. Ensure valid JSON syntax.');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/40 backdrop-blur-xs">
      <div
        id="modal-export-import"
        className="w-full max-w-2xl bg-white border border-zinc-200/90 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] animate-in fade-in zoom-in-95 duration-200 text-zinc-900"
      >
        {/* Header with Tabs */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-zinc-200/80 bg-zinc-50/50">
          <div className="flex items-center gap-1.5 p-1 rounded-xl bg-zinc-100 border border-zinc-200">
            <button
              onClick={() => {
                setTab('export');
                setImportError(null);
                setImportSuccess(null);
              }}
              className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-semibold transition-all ${
                tab === 'export'
                  ? 'bg-white text-zinc-900 shadow-2xs'
                  : 'text-zinc-600 hover:text-zinc-900'
              }`}
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Design</span>
            </button>

            <button
              onClick={() => {
                setTab('import');
                setImportError(null);
                setImportSuccess(null);
              }}
              className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-semibold transition-all ${
                tab === 'import'
                  ? 'bg-white text-zinc-900 shadow-2xs'
                  : 'text-zinc-600 hover:text-zinc-900'
              }`}
            >
              <Upload className="w-3.5 h-3.5" />
              <span>Import Project</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-zinc-400 hover:text-zinc-700 hover:bg-zinc-100 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 p-5 overflow-y-auto space-y-4">
          {tab === 'export' && (
            <div className="space-y-4">
              <div>
                <label className="block text-3xs font-semibold uppercase tracking-wider text-zinc-500 mb-2">
                  Select Standard Export Format
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  <button
                    onClick={() => setExportFormat('json')}
                    className={`flex flex-col items-center gap-1.5 p-3 rounded-xl border text-center transition-all ${
                      exportFormat === 'json'
                        ? 'bg-zinc-900 border-zinc-900 text-white shadow-2xs'
                        : 'bg-zinc-50/60 border-zinc-200 text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900'
                    }`}
                  >
                    <FileJson className={`w-5 h-5 ${exportFormat === 'json' ? 'text-zinc-200' : 'text-zinc-700'}`} />
                    <span className="text-xs font-semibold">JSON Project</span>
                    <span className={`text-4xs ${exportFormat === 'json' ? 'text-zinc-300' : 'text-zinc-500'}`}>Variables & Locks</span>
                  </button>

                  <button
                    onClick={() => setExportFormat('png')}
                    className={`flex flex-col items-center gap-1.5 p-3 rounded-xl border text-center transition-all ${
                      exportFormat === 'png'
                        ? 'bg-zinc-900 border-zinc-900 text-white shadow-2xs'
                        : 'bg-zinc-50/60 border-zinc-200 text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900'
                    }`}
                  >
                    <ImageIcon className={`w-5 h-5 ${exportFormat === 'png' ? 'text-zinc-200' : 'text-zinc-700'}`} />
                    <span className="text-xs font-semibold">PNG Image</span>
                    <span className={`text-4xs ${exportFormat === 'png' ? 'text-zinc-300' : 'text-zinc-500'}`}>Direct Snapshot</span>
                  </button>

                  <button
                    onClick={() => setExportFormat('html')}
                    className={`flex flex-col items-center gap-1.5 p-3 rounded-xl border text-center transition-all ${
                      exportFormat === 'html'
                        ? 'bg-zinc-900 border-zinc-900 text-white shadow-2xs'
                        : 'bg-zinc-50/60 border-zinc-200 text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900'
                    }`}
                  >
                    <FileCode className={`w-5 h-5 ${exportFormat === 'html' ? 'text-zinc-200' : 'text-zinc-700'}`} />
                    <span className="text-xs font-semibold">Standalone HTML</span>
                    <span className={`text-4xs ${exportFormat === 'html' ? 'text-zinc-300' : 'text-zinc-500'}`}>Runnable Pts.js</span>
                  </button>

                  <button
                    onClick={() => setExportFormat('svg')}
                    className={`flex flex-col items-center gap-1.5 p-3 rounded-xl border text-center transition-all ${
                      exportFormat === 'svg'
                        ? 'bg-zinc-900 border-zinc-900 text-white shadow-2xs'
                        : 'bg-zinc-50/60 border-zinc-200 text-zinc-600 hover:bg-zinc-100 hover:text-zinc-900'
                    }`}
                  >
                    <FileText className={`w-5 h-5 ${exportFormat === 'svg' ? 'text-zinc-200' : 'text-zinc-700'}`} />
                    <span className="text-xs font-semibold">Vector SVG</span>
                    <span className={`text-4xs ${exportFormat === 'svg' ? 'text-zinc-300' : 'text-zinc-500'}`}>Scalable graphics</span>
                  </button>
                </div>
              </div>

              {/* Code Preview Box */}
              <div>
                <div className="flex items-center justify-between text-3xs font-medium text-zinc-600 mb-1.5">
                  <span>File Output Preview</span>
                  {exportFormat !== 'png' && (
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1 text-zinc-800 hover:text-black font-semibold text-3xs"
                    >
                      {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copied ? 'Copied!' : 'Copy Code'}</span>
                    </button>
                  )}
                </div>

                <div className="p-3 bg-zinc-900 border border-zinc-800 rounded-xl font-mono text-3xs text-zinc-200 max-h-48 overflow-y-auto leading-relaxed">
                  {exportFormat === 'json' && (
                    <pre>{JSON.stringify(getProjectJsonObject(), null, 2)}</pre>
                  )}
                  {exportFormat === 'html' && <pre>{getStandaloneHtmlCode()}</pre>}
                  {exportFormat === 'svg' && <pre>{getSvgCode()}</pre>}
                  {exportFormat === 'png' && (
                    <div className="text-center py-6 text-zinc-400 font-sans">
                      High-resolution PNG will be generated directly from the live canvas viewport with current particle positions and glow states.
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {tab === 'import' && (
            <div className="space-y-4">
              {/* File Dropzone */}
              <div
                onClick={() => fileInputRef.current?.click()}
                className="border-2 border-dashed border-zinc-300 hover:border-zinc-700 rounded-xl p-6 text-center cursor-pointer bg-zinc-50/50 hover:bg-zinc-100/60 transition-colors"
              >
                <Upload className="w-8 h-8 mx-auto text-zinc-400 mb-2 stroke-zinc-500" />
                <h4 className="text-xs font-semibold text-zinc-800">Upload Project File (.json)</h4>
                <p className="text-3xs text-zinc-500 mt-1">
                  Drag and drop your exported Pts.js project file here, or click to browse
                </p>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".json,application/json"
                  onChange={handleFileUpload}
                  className="hidden"
                />
              </div>

              {/* Paste JSON Text Area */}
              <form onSubmit={handlePasteSubmit} className="space-y-2">
                <label className="block text-3xs font-medium text-zinc-600">
                  Or Paste Project JSON Directly
                </label>
                <textarea
                  value={pasteJsonText}
                  onChange={(e) => setPasteJsonText(e.target.value)}
                  placeholder="Paste JSON configuration payload here..."
                  rows={4}
                  className="w-full px-3 py-2 bg-white border border-zinc-300 rounded-xl font-mono text-3xs text-zinc-800 placeholder-zinc-400 focus:outline-hidden focus:border-zinc-600"
                />
                <div className="flex justify-end">
                  <button
                    type="submit"
                    className="px-3.5 py-1.5 rounded-lg bg-zinc-100 hover:bg-zinc-200 text-zinc-800 text-xs font-medium transition-colors border border-zinc-300"
                  >
                    Load Pasted JSON
                  </button>
                </div>
              </form>

              {/* Status notifications */}
              {importError && (
                <div className="flex items-center gap-2 p-2.5 rounded-lg bg-red-50 border border-red-200 text-red-700 text-xs">
                  <AlertCircle className="w-4 h-4 shrink-0 text-red-600" />
                  <span>{importError}</span>
                </div>
              )}

              {importSuccess && (
                <div className="flex items-center gap-2 p-2.5 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs">
                  <Check className="w-4 h-4 shrink-0 text-emerald-600" />
                  <span>{importSuccess}</span>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-5 py-3 border-t border-zinc-200 bg-zinc-50/50 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-3.5 py-1.5 rounded-lg text-xs font-medium text-zinc-600 hover:text-zinc-900 hover:bg-zinc-100 transition-colors"
          >
            Cancel
          </button>

          {tab === 'export' ? (
            <button
              onClick={handleExport}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-zinc-900 hover:bg-black text-white font-medium text-xs transition-colors shadow-2xs"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download {exportFormat.toUpperCase()}</span>
            </button>
          ) : (
            <span className="text-3xs text-zinc-400 font-mono">
              Accepts .json schema with engine & dynamic variables
            </span>
          )}
        </div>
      </div>
    </div>
  );
};
